maintainer       "Aaron Bull Schaefer"
maintainer_email "aaron@elasticdog.com"
license          "MIT"
description      "Installs/Configures vagrant_main"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends          "ack"
depends          "dotfiles"
depends          "gems"
depends          "git"
depends          "htop"
depends          "mercurial"
depends          "tmux"
depends          "vim"
depends          "zsh"
